[package]
name = "justcommit"
description = "AI powered commit message generator."
version = "0.1.0"
authors = ["Shuntaro Nishizawa"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
chatgpt_rs = "1.1.13"
clap = { version = "4.3.21", features = ["derive"] }
tokio = { version = "1.31.0", features = ["macros", "rt-multi-thread"] }
