name: Release

on:
  workflow_call:
    inputs:
      tag-name:
        type: string
        description: "Tag to release"
        required: true
  workflow_dispatch:
    inputs:
      tag-name:
        type: string
        description: "Tag to release"
        required: true
      dry-run:
        type: boolean
        description: "Don't actually release"
        required: false
        default: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest

          - target: x86_64-apple-darwin
            os: macos-latest

          - target: aarch64-apple-darwin
            os: macos-latest

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            rustflags: -C target-feature=+crt-static
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Setup | Cache
        uses: Swatinem/rust-cache@v2

      - name: Setup | Cross
        if: matrix.os == 'ubuntu-latest'
        uses: taiki-e/install-action@cross

      - name: Build | Build
        env:
          RUSTFLAGS: ${{ matrix.rustflags || '' }}
        shell: bash
        run: |
          if [[ ${{ matrix.os }} != 'ubuntu-latest' ]]; then
            build_command="cargo"
          else
            build_command="cross"
          fi

          ${build_command} build --release --locked --target ${{ matrix.target }}

      - name: Post Build | Get package info
        id: package-info
        shell: bash
        run: |
          if [[ ${{ matrix.os }} != 'windows-latest' ]]; then
            echo "name=justcommit-${{ matrix.target }}.tar.gz" >> $GITHUB_OUTPUT
          else
            echo "name=justcommit-${{ matrix.target }}.zip" >> $GITHUB_OUTPUT
          fi

      - name: Post Build | Prepare artifact
        shell: bash
        run: |
          if [[ ${{ matrix.os }} != 'windows-latest' ]]; then
            archive_command="tar czvf"
          else
            archive_command="7z a"
          fi

          ${archive_command} "${{ steps.package-info.outputs.name }}" "target/${{ matrix.target }}/release/justcommit" README.md LICENSE

      - name: Release | Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.package-info.outputs.name }}
          path: ${{ steps.package-info.outputs.name }}

      - name: Release | Upload asset
        if: ${{ !inputs.dry-run }}
        run: gh release upload ${{ inputs.tag-name }} ${{ steps.package-info.outputs.name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
